version: '3'

services:
  server: 
    build:
      context: .
    image: runtime
    command: ['gunicorn', '--config', './src/gunicorn.conf.py']
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER: amqp://guest:guest@broker:5672
      CELERY_BACKEND: mongodb://guest:guest@db:27017/?authMechanism=DEFAULT&authSource=admin
      GUNICORN_HOST: 0.0.0.0:8000
    networks:
      - private
      - public
  
  worker:
    image: runtime
    command:
      - celery
      - --app
      - src.worker
      - worker
      - --hostname
      - worker@%h
      - --concurrency
      - '1' 
      - --loglevel
      - INFO
    environment:
      CELERY_BROKER: amqp://guest:guest@broker:5672
      CELERY_BACKEND: mongodb://guest:guest@db:27017/?authMechanism=DEFAULT&authSource=admin
    networks:
      - private

  celery-ui:
    image: runtime
    command:
      - celery
      - --app
      - src.worker
      - flower
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER: amqp://guest:guest@broker:5672
      CELERY_BACKEND: mongodb://guest:guest@db:27017/?authMechanism=DEFAULT&authSource=admin
    networks:
      - public
      - private

  broker:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - "5672"
    ports:
      - "15672:15672"
    networks:
      - public
      - private

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db:rw
    networks:
      - public
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true

volumes:
  mongodb_data: {}
