version: '3'

services:
  server: 
    build:
      context: .
    image: runtime
    command: ['gunicorn', '--config', './src/gunicorn.conf.py']
    ports:
      - "${HTTP_SERVER_PUBLIC_PORT}:8000"
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
      GUNICORN_HOST: 0.0.0.0:8000
    networks:
      - private
      - public
  
  worker:
    image: runtime
    command:
      - celery
      - --app
      - src.worker
      - worker
      - --hostname
      - worker@%h
      - --concurrency
      - '1' 
      - --loglevel
      - INFO
      - --events
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
    networks:
      - private

  celery-ui:
    image: runtime
    command:
      - celery
      - --app
      - src.worker
      - flower
    ports:
      - "${CELERY_UI_PUBLIC_PORT}:5555"
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
    networks:
      - public
      - private

  broker:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    expose:
      - "5672"
    ports:
      - "${RABBITMQ_UI_PUBLIC_PORT}:15672"
    networks:
      - public
      - private

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PUBLIC_PORT}:27017"
    volumes: 
      - mongodb_data:/data/db:rw
    networks:
      - public
      - private

networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true

volumes:
  mongodb_data: {}
