POST http://localhost:8000/api/tasks/long-add
Content-Type: application/json

{
  "a": 4,
  "b": 5
}

###

POST http://localhost:8000/api/tasks/fibonacci
Content-Type: application/json

{
  "n": 10
}

###

GET http://localhost:8000/api/tasks/894b7cfc-05ed-4acd-a7c1-dabd41cae191

